title:              Clean Blog
email:              sangjoonlee8787@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/home"
url:                "http://localhost:4000/"

# Social Profiles
twitter_username:   
github_username:    lawrencelee-curry
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
